### ISSUE TITLE
Gemini is not sufficiently explicit about sending to native devices

### ISSUE THREAD

**Issue by bossmc** [Metaswitch/gemini#20]
To send to a native device, Gemini adds the twin-prefix (if provided) and adds an `Accept-Contact: *;g.3gpp.ics` header.  Unfortunately, this is only a suggestion and Clearwater happily forks the call to all devices registered under that username.  The correct header should have `;explicit;require` appended to ensure non-native devices are not chosen for forking.

**Comment by bossmc** [comment]
See also #18 and #19 for related issues.

**Comment by bossmc** [comment]
#16 is also similar (I've added comments to allow that PR to fix this issue too).

**Comment by rkd-msw** [comment]
I'll fix under #16.

**Comment by rkd-msw** [comment]
Fixed.
